#ifndef CDTTABLEEXPORTER_GLOBAL_H
#define CDTTABLEEXPORTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CDTTABLEEXPORTER_LIBRARY)
#  define CDTTABLEEXPORTER_EXPORT Q_DECL_EXPORT
#else
#  define CDTTABLEEXPORTER_EXPORT Q_DECL_IMPORT
#endif

#endif // CDTTABLEEXPORTER_GLOBAL_H
