#ifndef QTCOLORPICKER_GLOBAL_H
#define QTCOLORPICKER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTCOLORPICKER_LIBRARY)
#  define QTCOLORPICKER_EXPORT Q_DECL_EXPORT
#else
#  define QTCOLORPICKER_EXPORT Q_DECL_IMPORT
#endif

#endif // QTCOLORPICKER_GLOBAL_H
