#ifndef QPROPERTYEDITOR_GLOBAL_H
#define QPROPERTYEDITOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QPROPERTYEDITOR_LIBRARY)
#  define QPROPERTYEDITOR_EXPORT Q_DECL_EXPORT
#else
#  define QPROPERTYEDITOR_EXPORT Q_DECL_IMPORT
#endif

#endif // QPROPERTYEDITOR_GLOBAL_H
