#ifndef QGSWIDGETS_GLOBAL_H
#define QGSWIDGETS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QGSWIDGETS_LIBRARY)
#  define QGSWIDGETS_EXPORT Q_DECL_EXPORT
#else
#  define QGSWIDGETS_EXPORT Q_DECL_IMPORT
#endif

#endif // QGSWIDGETS_GLOBAL_H
