#ifndef CDTFILESYSTEM_GLOBAL_H
#define CDTFILESYSTEM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CDTFILESYSTEM_LIBRARY)
#  define CDTFILESYSTEM_EXPORT Q_DECL_EXPORT
#else
#  define CDTFILESYSTEM_EXPORT Q_DECL_IMPORT
#endif

#endif // CDTFILESYSTEM_GLOBAL_H
