#ifndef CDTHISTOGRAMPLOT_GLOBAL_H
#define CDTHISTOGRAMPLOT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CDTHISTOGRAMPLOT_LIBRARY)
#  define CDTHISTOGRAMPLOT_EXPORT Q_DECL_EXPORT
#else
#  define CDTHISTOGRAMPLOT_EXPORT Q_DECL_IMPORT
#endif

#endif // CDTHISTOGRAMPLOT_GLOBAL_H
