#ifndef CDTTASKCLIENT_GLOBAL_H
#define CDTTASKCLIENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CDTTASKCLIENT_LIBRARY)
#  define CDTTASKCLIENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CDTTASKCLIENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CDTTASKCLIENT_GLOBAL_H
