#ifndef CDTCLASSIFIERASSESSMENTWIDGET_GLOBAL_H
#define CDTCLASSIFIERASSESSMENTWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CDTCLASSIFIERASSESSMENTWIDGET_LIBRARY)
#  define CDTCLASSIFIERASSESSMENTWIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CDTCLASSIFIERASSESSMENTWIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CDTCLASSIFIERASSESSMENTWIDGET_GLOBAL_H
